### ISSUE TITLE
Add "tips" to the main page?

### ISSUE THREAD

**Issue by kevinlinxc** [stemformulas/stemformulas.github.io#12]
Some things could be made clearer about the site's functionality but would be weird as text anywhere, e.g.

- Hitting `/` to focus the header search bar on every page except the main one
- Hitting enter choosing the first option of a search even though its not highlighted

We could put tips under the main page search bar, and it could also have some interesting stem facts

**Comment by ihsan314** [comment]
Related, what about embedding the introductory video posted to LinkedIn somewhere on the site?

I didn't really figure out the basics of operating the site until I watched the video.

**Comment by kevinlinxc** [comment]
This is a really good idea, I'll render a version for the README.

**Comment by kevinlinxc** [comment]
Over time I've added tips to the front page and instructions around the site.
<img width="614" alt="image" src="https://github.com/stemformulas/stemformulas.github.io/assets/44324811/99800768-d7c6-41a3-8ee6-76b493153ebf">
<img width="436" alt="image" src="https://github.com/stemformulas/stemformulas.github.io/assets/44324811/c8590e33-b903-4353-920c-2f6a85df8f45">

I consider this closed.
